
[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.75
startup_mode = "Windowed"

[window.dimensions]
columns = 88
lines = 24

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
import = ["/home/jarvis/.config/alacritty/colorschemes/wallust.toml", "/home/jarvis/.config/alacritty/fonts.toml"]
