# colors for foot terminal
# You can use this template by adding the following to wallust.toml:
# foot = { template = "foot.ini", target = "~/.config/foot/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/foot/colors.ini


[colors]
background=000003
foreground=F1F3F7

# Normal/regular colors (color palette 0-7)
regular0=000004  # black
regular1=8D7288  # red
regular2=678F98  # green
regular3=66909C  # yellow
regular4=6B9186  # blue
regular5=B09868  # magenta
regular6=A2A6AF  # cyan
regular7=E3E6EC  # white

# Bright colors (color palette 8-15)
bright0=9FA1A5   # bright black
bright1=B48EAD   # bright red
bright2=89BFCB   # bright green
bright3=88C0D0   # bright yellow
bright4=8FC2B3   # bright blue
bright5=EBCB8B   # bright magenta
bright6=D8DEE9   # bright cyan
bright7=E3E6EC   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
