# colors for foot terminal
# You can use this template by adding the following to wallust.toml:
# foot = { template = "foot.ini", target = "~/.config/foot/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/foot/colors.ini


[colors]
background=000004
foreground=DDE8D9

# Normal/regular colors (color palette 0-7)
regular0=17191B  # black
regular1=676F78  # red
regular2=86776A  # green
regular3=5F7A82  # yellow
regular4=7A7580  # blue
regular5=99836B  # magenta
regular6=778E6E  # cyan
regular7=C7D6C1  # white

# Bright colors (color palette 8-15)
bright0=8B9587   # bright black
bright1=6F7A86   # bright red
bright2=8A715D   # bright green
bright3=68909A   # bright yellow
bright4=908898   # bright blue
bright5=CCAE8F   # bright magenta
bright6=9FBD93   # bright cyan
bright7=C7D6C1   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
