# colors for foot terminal
# You can use this template by adding the following to wallust.toml:
# foot = { template = "foot.ini", target = "~/.config/foot/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/foot/colors.ini


[colors]
background=242230
foreground=FFF5E0

# Normal/regular colors (color palette 0-7)
regular0=504D5E  # black
regular1=4C9083  # red
regular2=85947A  # green
regular3=7490A6  # yellow
regular4=7E98B0  # blue
regular5=B6A679  # magenta
regular6=BFAA7C  # cyan
regular7=F6E9CA  # white

# Bright colors (color palette 8-15)
bright0=ACA38D   # bright black
bright1=359E8C   # bright red
bright2=A9BE99   # bright green
bright3=9BC0DD   # bright yellow
bright4=A8CBEB   # bright blue
bright5=F3DDA2   # bright magenta
bright6=FEE3A5   # bright cyan
bright7=F6E9CA   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
