[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#151615'
foreground = '#E2E3EF'

[colors.cursor]
text = '#E2E3EF'
cursor = '#A293A5'

[colors.normal]
black   = '#3F4140'
red     = '#485773'
green   = '#866E80'
yellow  = '#65A0C7'
blue    = '#74A9D3'
magenta = '#9FA0CD'
cyan    = '#ACB0D2'
white   = '#CDCFE0'

[colors.bright]
black   = '#8F919D'
red     = '#485773'
green   = '#866E80'
yellow  = '#65A0C7'
blue    = '#74A9D3'
magenta = '#9FA0CD'
cyan    = '#ACB0D2'
white   = '#CDCFE0'