[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#16161D'
foreground = '#E5F1FA'

[colors.cursor]
text = '#E5F1FA'
cursor = '#E5F1FA'

[colors.normal]
black   = '#40414A'
red     = '#3C5C77'
green   = '#70595B'
yellow  = '#7FADD0'
blue    = '#B3AFCA'
magenta = '#AFD2E2'
cyan    = '#B4D7F0'
white   = '#D1E3EF'

[colors.bright]
black   = '#929FA7'
red     = '#3C5C77'
green   = '#70595B'
yellow  = '#7FADD0'
blue    = '#B3AFCA'
magenta = '#AFD2E2'
cyan    = '#B4D7F0'
white   = '#D1E3EF'