[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#121115'
foreground = '#FCF8F5'

[colors.cursor]
text = '#FCF8F5'
cursor = '#F2D0AE'

[colors.normal]
black   = '#3A393D'
red     = '#DB8FDA'
green   = '#E7A867'
yellow  = '#F8B48B'
blue    = '#54D9F5'
magenta = '#86DEB4'
cyan    = '#F6EBE3'
white   = '#F2EDE9'

[colors.bright]
black   = '#A9A6A3'
red     = '#DB8FDA'
green   = '#E7A867'
yellow  = '#F8B48B'
blue    = '#54D9F5'
magenta = '#86DEB4'
cyan    = '#F6EBE3'
white   = '#F2EDE9'