[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#161819'
foreground = '#D1FEC2'

[colors.cursor]
text = '#D1FEC2'
cursor = '#8BBC83'

[colors.normal]
black   = '#404344'
red     = '#427C65'
green   = '#608C5F'
yellow  = '#E2553F'
blue    = '#29CFC6'
magenta = '#73D46E'
cyan    = '#7CFC51'
white   = '#B5F5A0'

[colors.bright]
black   = '#7FAC70'
red     = '#427C65'
green   = '#608C5F'
yellow  = '#E2553F'
blue    = '#29CFC6'
magenta = '#73D46E'
cyan    = '#7CFC51'
white   = '#B5F5A0'