[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#1F2121'
foreground = '#DFE7DA'

[colors.cursor]
text = '#DFE7DA'
cursor = '#CEC4B2'

[colors.normal]
black   = '#4A4D4D'
red     = '#B27A7D'
green   = '#998677'
yellow  = '#828D85'
blue    = '#75907F'
magenta = '#719472'
cyan    = '#809276'
white   = '#C8D4C1'

[colors.bright]
black   = '#8C9587'
red     = '#E39094'
green   = '#BDA28B'
yellow  = '#9BAB9F'
blue    = '#93B9A0'
magenta = '#8DBD8E'
cyan    = '#A2BB94'
white   = '#C8D4C1'