[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#121219'
foreground = '#D9E5F5'

[colors.cursor]
text = '#D9E5F5'
cursor = '#D9E5F5'

[colors.normal]
black   = '#3C3C45'
red     = '#3A4967'
green   = '#41546A'
yellow  = '#416089'
blue    = '#A7A6D1'
magenta = '#ABA8C0'
cyan    = '#93B4E1'
white   = '#C0D1E8'

[colors.bright]
black   = '#8792A2'
red     = '#3A4967'
green   = '#41546A'
yellow  = '#416089'
blue    = '#A7A6D1'
magenta = '#ABA8C0'
cyan    = '#93B4E1'
white   = '#C0D1E8'