[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#121314'
foreground = '#F2E8DB'

[colors.cursor]
text = '#F2E8DB'
cursor = '#B5BEB0'

[colors.normal]
black   = '#3C3D3F'
red     = '#BD6E49'
green   = '#789585'
yellow  = '#3A99C1'
blue    = '#D9A28A'
magenta = '#A9B5B8'
cyan    = '#DBBD98'
white   = '#E5D6C3'

[colors.bright]
black   = '#A09689'
red     = '#BD6E49'
green   = '#789585'
yellow  = '#3A99C1'
blue    = '#D9A28A'
magenta = '#A9B5B8'
cyan    = '#DBBD98'
white   = '#E5D6C3'