[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#101016'
foreground = '#DDFAFD'

[colors.cursor]
text = '#DDFAFD'
cursor = '#DDFAFD'

[colors.normal]
black   = '#3B3A42'
red     = '#4C5683'
green   = '#4E5E79'
yellow  = '#75B6F0'
blue    = '#76C9EC'
magenta = '#85D6F7'
cyan    = '#9EF0FA'
white   = '#C6EFF4'

[colors.bright]
black   = '#8BA7AB'
red     = '#4C5683'
green   = '#4E5E79'
yellow  = '#75B6F0'
blue    = '#76C9EC'
magenta = '#85D6F7'
cyan    = '#9EF0FA'
white   = '#C6EFF4'