[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#FFFCF9'
foreground = '#0A1021'

[colors.cursor]
text = '#0A1021'
cursor = '#442C30'

[colors.normal]
black   = '#FFFCF9'
red     = '#273318'
green   = '#5E362F'
yellow  = '#373717'
blue    = '#1C3323'
magenta = '#351E19'
cyan    = '#111A38'
white   = '#0A1021'

[colors.bright]
black   = '#A57D71'
red     = '#354420'
green   = '#7D493E'
yellow  = '#4A4A1F'
blue    = '#26442F'
magenta = '#472821'
cyan    = '#16224A'
white   = '#03050B'