[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#030007'
foreground = '#F2FAFE'

[colors.cursor]
text = '#F2FAFE'
cursor = '#8FB6D4'

[colors.normal]
black   = '#0F0A12'
red     = '#A07056'
green   = '#4180B1'
yellow  = '#9E8780'
blue    = '#ABD5F7'
magenta = '#D1ECFB'
cyan    = '#D9F0FD'
white   = '#E4EFF5'

[colors.bright]
black   = '#9FA7AC'
red     = '#A07056'
green   = '#4180B1'
yellow  = '#9E8780'
blue    = '#ABD5F7'
magenta = '#D1ECFB'
cyan    = '#D9F0FD'
white   = '#E4EFF5'