[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#0C0E10'
foreground = '#CFE3F7'

[colors.cursor]
text = '#CFE3F7'
cursor = '#6A7C90'

[colors.normal]
black   = '#37393B'
red     = '#3E4449'
green   = '#3D4652'
yellow  = '#506B8B'
blue    = '#62748B'
magenta = '#757B81'
cyan    = '#5884AE'
white   = '#B2CFEB'

[colors.bright]
black   = '#7C91A5'
red     = '#3F474E'
green   = '#3E4A5A'
yellow  = '#587BA6'
blue    = '#6881A1'
magenta = '#757F89'
cyan    = '#75B0E8'
white   = '#B2CFEB'