[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#110F0F'
foreground = '#EADED2'

[colors.cursor]
text = '#EADED2'
cursor = '#AF9783'

[colors.normal]
black   = '#3C393A'
red     = '#7E6453'
green   = '#7D6858'
yellow  = '#767077'
blue    = '#6E728A'
magenta = '#A3773A'
cyan    = '#937960'
white   = '#D9C8B7'

[colors.bright]
black   = '#988C80'
red     = '#95725C'
green   = '#947762'
yellow  = '#847B86'
blue    = '#797EA1'
magenta = '#C58122'
cyan    = '#C4A280'
white   = '#D9C8B7'