[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#151517'
foreground = '#FBE5C7'

[colors.cursor]
text = '#FBE5C7'
cursor = '#FBE5C7'

[colors.normal]
black   = '#404042'
red     = '#4F4F55'
green   = '#6A4945'
yellow  = '#D88746'
blue    = '#FD802E'
magenta = '#EEA178'
cyan    = '#F4B55E'
white   = '#F1D2A6'

[colors.bright]
black   = '#A99374'
red     = '#4F4F55'
green   = '#6A4945'
yellow  = '#D88746'
blue    = '#FD802E'
magenta = '#EEA178'
cyan    = '#F4B55E'
white   = '#F1D2A6'