[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#0D0E10'
foreground = '#EBE5E6'

[colors.cursor]
text = '#EBE5E6'
cursor = '#EBE5E6'

[colors.normal]
black   = '#38393B'
red     = '#43464F'
green   = '#454655'
yellow  = '#8C7888'
blue    = '#7382A9'
magenta = '#8C7D94'
cyan    = '#C7B3B9'
white   = '#DAD1D3'

[colors.bright]
black   = '#999294'
red     = '#43464F'
green   = '#454655'
yellow  = '#8C7888'
blue    = '#7382A9'
magenta = '#8C7D94'
cyan    = '#C7B3B9'
white   = '#DAD1D3'