[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#010B0E'
foreground = '#FCF9FB'

[colors.cursor]
text = '#FCF9FB'
cursor = '#BCCFD2'

[colors.normal]
black   = '#1B2325'
red     = '#677C84'
green   = '#658385'
yellow  = '#7E838D'
blue    = '#86A1A0'
magenta = '#9DAAAC'
cyan    = '#BAB2B7'
white   = '#F3EEF1'

[colors.bright]
black   = '#AAA6A9'
red     = '#7F9CA8'
green   = '#7CA6A9'
yellow  = '#A7AEBC'
blue    = '#B3D6D6'
magenta = '#D2E3E5'
cyan    = '#F8EDF4'
white   = '#F3EEF1'