[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#232025'
foreground = '#FDF6FD'

[colors.cursor]
text = '#FDF6FD'
cursor = '#F1D9F2'

[colors.normal]
black   = '#4A464C'
red     = '#BE805D'
green   = '#AC8DAE'
yellow  = '#B08FAB'
blue    = '#B09D4F'
magenta = '#94A3B9'
cyan    = '#BBACBA'
white   = '#F4EAF3'

[colors.bright]
black   = '#ABA4AA'
red     = '#FDAB7C'
green   = '#E6BDE8'
yellow  = '#EBBEE4'
blue    = '#EAD169'
magenta = '#C5DAF7'
cyan    = '#F9E6F9'
white   = '#F4EAF3'