[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#1D1B18'
foreground = '#EFF4F8'

[colors.cursor]
text = '#EFF4F8'
cursor = '#B6C199'

[colors.normal]
black   = '#44423F'
red     = '#5B8D80'
green   = '#7C8E3A'
yellow  = '#BB92A7'
blue    = '#C0B7D0'
magenta = '#B6CDD7'
cyan    = '#D2DFEB'
white   = '#E0E7ED'

[colors.bright]
black   = '#9DA1A6'
red     = '#5B8D80'
green   = '#7C8E3A'
yellow  = '#BB92A7'
blue    = '#C0B7D0'
magenta = '#B6CDD7'
cyan    = '#D2DFEB'
white   = '#E0E7ED'