[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#0F0F13'
foreground = '#D6FAFE'

[colors.cursor]
text = '#D6FAFE'
cursor = '#D6FAFE'

[colors.normal]
black   = '#3A3A3E'
red     = '#5A63A9'
green   = '#B4628D'
yellow  = '#858346'
blue    = '#DE5B48'
magenta = '#39AFE1'
cyan    = '#89F1FC'
white   = '#BBF0F5'

[colors.bright]
black   = '#83A8AB'
red     = '#5A63A9'
green   = '#B4628D'
yellow  = '#858346'
blue    = '#DE5B48'
magenta = '#39AFE1'
cyan    = '#89F1FC'
white   = '#BBF0F5'