[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#27262A'
foreground = '#ECE2F3'

[colors.cursor]
text = '#ECE2F3'
cursor = '#ECE2F3'

[colors.normal]
black   = '#535156'
red     = '#605A6B'
green   = '#7A5A8C'
yellow  = '#7F778A'
blue    = '#B289B9'
magenta = '#C093D1'
cyan    = '#CAABDC'
white   = '#DCCCE5'

[colors.bright]
black   = '#9A8FA0'
red     = '#605A6B'
green   = '#7A5A8C'
yellow  = '#7F778A'
blue    = '#B289B9'
magenta = '#C093D1'
cyan    = '#CAABDC'
white   = '#DCCCE5'