[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#CFD6D6'
foreground = '#020A0A'

[colors.cursor]
text = '#020A0A'
cursor = '#20453F'

[colors.normal]
black   = '#F8FFFF'
red     = '#425666'
green   = '#2E6057'
yellow  = '#2D4D55'
blue    = '#173D25'
magenta = '#152E45'
cyan    = '#031010'
white   = '#020A0A'

[colors.bright]
black   = '#5B7A7B'
red     = '#597389'
green   = '#6A9C94'
yellow  = '#698991'
blue    = '#1F5131'
magenta = '#1B3D5C'
cyan    = '#041616'
white   = '#010303'