[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#152528'
foreground = '#E3E4E5'

[colors.cursor]
text = '#E3E4E5'
cursor = '#837B67'

[colors.normal]
black   = '#B8BABB'
red     = '#809276'
green   = '#719472'
yellow  = '#75907F'
blue    = '#828D85'
magenta = '#998677'
cyan    = '#B27A7D'
white   = '#495443'

[colors.bright]
black   = '#728368'
red     = '#A2BB94'
green   = '#8DBD8E'
yellow  = '#93B9A0'
blue    = '#9BAB9F'
magenta = '#BDA28B'
cyan    = '#E39094'
white   = '#C8D4C1'