[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#1C171C'
foreground = '#FDF0D5'

[colors.cursor]
text = '#FDF0D5'
cursor = '#FDF0D5'

[colors.normal]
black   = '#484148'
red     = '#5D4661'
green   = '#5E4865'
yellow  = '#FE77F7'
blue    = '#ED8DE8'
magenta = '#F6B485'
cyan    = '#FAD488'
white   = '#F4E1BB'

[colors.bright]
black   = '#AB9E83'
red     = '#5D4661'
green   = '#5E4865'
yellow  = '#FE77F7'
blue    = '#ED8DE8'
magenta = '#F6B485'
cyan    = '#FAD488'
white   = '#F4E1BB'