[window]
opacity = 0.9

[font]
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"
size = 12.0

[colors.primary]
background = '#795E15'
foreground = '#E2E3E5'

[colors.cursor]
text = '#E2E3E5'
cursor = '#50A395'

[colors.normal]
black   = '#9D9EA2'
red     = '#CAC4B6'
green   = '#CCC191'
yellow  = '#C2C1AF'
blue    = '#8CB5C0'
magenta = '#56B9AE'
cyan    = '#738873'
white   = '#706C61'

[colors.bright]
black   = '#AEA796'
red     = '#F8EFD7'
green   = '#FCE997'
yellow  = '#EBE9CA'
blue    = '#A8DEED'
magenta = '#5FE3D5'
cyan    = '#86A286'
white   = '#F3EFE2'