$wallpaper = /home/jarvis/Pictures/wallpapers/abstract.jpg
$background = rgb(0F1111)
$foreground = rgb(C1E5E6)
$cursor = rgb(80B1AF)
$color0 = rgb(3A3B3C)
$color1 = rgb(414A4A)
$color2 = rgb(5E8280)
$color3 = rgb(5F8885)
$color4 = rgb(6C8483)
$color5 = rgb(588A8A)
$color6 = rgb(3B888A)
$color7 = rgb(9ED1D3)
$color8 = rgb(6F9394)
$color9 = rgb(434F4F)
$color10 = rgb(528B86)
$color11 = rgb(408781)
$color12 = rgb(638B8A)
$color13 = rgb(439494)
$color14 = rgb(4EB5B8)
$color15 = rgb(9ED1D3)
