backend = "full"
#palette = "dark16"
#palette = "light16"
#palette = "darkcomp16"
#palette = "lightcomp16"
#palette = "softdark16"
#palette = "softlight16"
palette = "dark"
#palette = "light"

color_space = "lchmixed"
check_contrast = true
pywal = true
[templates]
hypr.template = "hypr.conf"
hypr.target = "~/.config/hypr/colors.conf"

zathura = { template = 'zathurarc', target = '~/.config/zathura/zathurarc' }


kitty.template = 'theme.conf'
kitty.target = '~/.config/kitty/theme.conf'

rofi.template = "theme.rasi"
rofi.target = "~/.config/rofi/theme.rasi"

swaync.template = "swaync.css"
swaync.target = "~/.config/swaync/colors.css"

waybar.template = "theme.css"
waybar.target = "~/.config/waybar/theme.css"

xresourcs.template = "Xresources"
xresourcs.target = "/home/jarvis/.Xresources"

spotify.template = "spotify"
spotify.target = "~/.config/spicetify/Themes/wal/color.ini"
spicetify.template = "spicetify.ini"
spicetify.target = "~/.config/spicetify/Themes/wallust/color.ini"

kdeglobal.template = "kdeglobals"
kdeglobal.target = "~/.config/kdeglobals"

kvantum.template = "kvantum.kvconfig"
#kvantum.target = "~/.config/Kvantum/wallust/wallust.kvconfig"
kvantum.target = "~/.config/Kvantum/KvArcDark#/KvArcDark#.kvconfig"

pywal.template = "pywal.json"
pywal.target = "~/.cache/wal/colors.json"

# xdpl.template = "xdpl.conf"
# xdpl.target = "~/.config/xdg-desktop-portal-luminous/config.toml"

ghostty.template = "ghostty.conf"
ghostty.target = "~/.config/ghostty/colors.conf"

discord.template = "discord.css"
discord.target = "~/.config/Vencord/themes/wallust.css"

alacritty.template = "alacritty.toml"
alacritty.target = "~/.config/alacritty/colorschemes/wallust.toml"


dunst.template = "dunstrc"
dunst.target = "~/.config/dunst/dunstrc"


