# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FACFA7
background         #131619
cursor             #7D766A

active_tab_foreground     #131619
active_tab_background     #FACFA7
inactive_tab_foreground   #FACFA7
inactive_tab_background   #131619

active_border_color   #FACFA7
inactive_border_color #131619
bell_border_color     #3A4A54

color0      #3D4145
color1		#3A4A54
color2		#3A4A54
color3		#3A4A54
color4		#735757
color5		#926252
color6		#C07127
color7		#F0B279
color8		#A87D55
color9		#3A4F5D
color10		#3A4F5D
color11		#3A4F5D
color12		#866161
color13		#B0705A
color14		#F27703
color15		#F0B279