# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FEF5DA
background         #231C1B
cursor             #E7A998

active_tab_foreground     #231C1B
active_tab_background     #FEF5DA
inactive_tab_foreground   #FEF5DA
inactive_tab_background   #231C1B

active_border_color   #FEF5DA
inactive_border_color #231C1B
bell_border_color     #9B6B5C

color0      #504745
color1		#9B6B5C
color2		#B2706C
color3		#97845C
color4		#94865A
color5		#A67E70
color6		#BDA970
color7		#F5E8C2
color8		#ACA288
color9		#B97560
color10		#D1665E
color11		#BB9E64
color12		#BDAB6C
color13		#D79F8C
color14		#FCE196
color15		#F5E8C2