# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DEE6F9
background         #1C1C21
cursor             #8E99BC

active_tab_foreground     #1C1C21
active_tab_background     #DEE6F9
inactive_tab_foreground   #DEE6F9
inactive_tab_background   #1C1C21

active_border_color   #DEE6F9
inactive_border_color #1C1C21
bell_border_color     #484C5D

color0      #47474E
color1		#484C5D
color2		#5D6684
color3		#616D87
color4		#7187B7
color5		#7783AC
color6		#7889B3
color7		#C7D2EE
color8		#8B93A7
color9		#4D5269
color10		#69749D
color11		#6E7EA1
color12		#779AE3
color13		#9EAFE5
color14		#A0B6EE
color15		#C7D2EE